# Common Labels
labels:
  app: "garbage-service"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "garbage-service"  

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "garbage_service_schema"
    image:
      repository: "garbage-service-db"

# Container Configs
image:
  repository: "garbage-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/garbage-service/health"
  readinessProbePath: "/garbage-service/health"
appType: java-spring

# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: /garbage-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: rainmaker-pt-calculator-group
  - name: KAFKA_TOPICS_BILLING_SLAB_SAVE_SERVICE
    value: save-pt-billingslab
  - name: KAFKA_TOPICS_BILLING_SLAB_UPDATE_SERVICE
    value: update-pt-billingslab
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_REPORT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: report
  - name: EGOV_REPORT_ENDPOINT_CREATE
    value: "/report/pdf-service/v1/_create"
  - name: EGOV_ALFRESCO_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hpud-dms-service
  - name: EGOV_ALFRESCO_ENDPOINT_UPLOAD
    value: "/hpud-dms-service/dms/uploadAttachments"
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_TRANSITION_PATH
    value: "/egov-workflow-v2/egov-wf/process/_transition"
  - name: WORKFLOW_BUSSINESS_SEARCH
    value: "/egov-workflow-v2/egov-wf/businessservice/_search"    
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_BILL_CONTEXT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_BILL_ENDPOINT_FETCH
    value: /billing-service/bill/v2/_fetchbill
  - name: EGOV_BILL_ENDPOINT_SEARCH
    value: /billing-service/bill/v2/_search
  - name: EGOV_DEMAND_CREATE_ENDPOINT
    value: /billing-service/demand/_create
  - name: EGOV_DEMAND_SEARCH_ENDPOINT
    value: /billing-service/demand/_search?tenantId={1}&businessService={2}&consumerCode={3}
  - name: EGOV_DEMAND_UPDATE_ENDPOINT
    value: /billing-service/demand/_update
  - name: EGOV_COLLECTIONSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: LOGGING_LEVEL_ORG_EGOV
    value: {{ index .Values "logging-level" | quote }}
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  {{- if index .Values "JAVA_ENABLE_DEBUG" }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "JAVA_ENABLE_DEBUG" | quote }}
  {{- end }}
  {{- if index .Values "CUSTOM_PB_ZERO_ASSESSMENT" }}
  - name: CUSTOM_PB_ZERO_ASSESSMENT
    value: {{ index .Values "CUSTOM_PB_ZERO_ASSESSMENT" | quote }}
  - name: CUSTOM_PB_ZERO_ASSESSMENTYEAR
    value: {{ index .Values "CUSTOM_PB_ZERO_ASSESSMENTYEAR" | quote }}
  - name: CUSTOM_PB_ZERO_ASSESSMENT_TENANTID
    value: {{ index .Values "CUSTOM_PB_ZERO_ASSESSMENT_TENANTID" | quote }}
  {{- end }}
  {{- if index .Values "custom-pb-firecess-logic" }}
  - name: CUSTOMIZATION_PBFIRECESSLOGIC
    value: {{ index .Values "custom-pb-firecess-logic" | quote }}
  {{- end }}
  - name: CUSTOMIZATION_ALLOWDEPRECIATIONONNORECEIPTS
    value: {{ index .Values "allow-depreciations" | quote }}
  - name: CUSTOMIZATION_UNBUILTAREA_PRORATED
    value: {{ index .Values "unbuiltarea-prorated" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: PT_MODULE_MINPAYABLE_AMOUNT
    value: "100"
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"      
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
# Additional Container Envs