# Common Labels
labels:
  app: "asset-services"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "asset-services"  

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "asset_services_schema"
    image:
      repository: "upyoguddhp/asset-services-db"

# Container Configs
image:
  repository: "upyoguddhp/asset-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/asset-services/health"
  readinessProbePath: "/asset-services/health"
appType: java-spring
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_TL_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: tl-calculator
  - name: EGOV_PROPERTY_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: property-services
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_URL_SHORTNER_ENDPOINT
    value: {{ index .Values "egov-url-shortner-endpoint" | quote }}
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-tl-services
  - name: PERSISTER_SAVE_TRADELICENSE_TOPIC
    value: save-tl-tradelicense
  - name: PERSISTER_UPDATE_TRADELICENSE_TOPIC
    value: update-tl-tradelicense
  - name: PERSISTER_UPDATE_TRADELICENSE_WORKFLOW_TOPIC
    value: update-tl-workflow
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_TRANSITION_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
  - name: EGOV_TL_DEFAULT_LIMIT
    value: {{ index .Values "tl-search-default-limit" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_IDGEN_TL_APPLICATIONNUM_FORMAT
    value: {{ index .Values "tl-application-num-format" | quote }}
  - name: KAFKA_TOPICS_RECEIPT_CREATE
    value: {{ index .Values "tl-payment-topic-name" | quote }}
  - name: EGOV_IDGEN_TL_LICENSENUMBER_FORMAT
    value: {{ index .Values "tl-license-num-format" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"     
  - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
    value: "true"
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USR_EVENTS_CREATE_TOPIC
    value: "persist-user-events-async"
  - name: EGOV_USR_EVENTS_PAY_LINK
    value: {{ index .Values "tl-userevents-pay-link" | quote }}
  - name: EGOV_MSG_PAY_LINK
    value: {{ index .Values "tl-msg-pay-link" | quote }}
  - name: EGOV_USR_EVENTS_PAY_CODE
    value: "PAY"
  - name: EGOV_USR_EVENTS_PAY_TRIGGERS
    value: "PENDINGPAYMENT"
  - name: NOTIFICATION_PDF_LINK
    value: {{ index .Values "pdf-link" | quote }}
  - name: NOTIFICATION_HOST_LINK
    value: {{ index .Values "host-link" | quote }}  
  {{- if index .Values "egov-location-hierarchytypecode" }}
  - name: EGOV_LOCATION_HIERARCHYTYPECODE
    value: {{ index .Values "egov-location-hierarchytypecode" | quote }}
  {{- end }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}